# Settings/Configuration shared among all environments.

# Internal Services
solr:
  user: <%= DockerSecrets.lookup(:solr_username) %>
  password: <%= DockerSecrets.lookup(:solr_password) %>
  url: <%= ENV['SOLR_URL'] %>
  instances: <%= ENV['SOLR_INSTANCES'] %>
  configset: <%= ENV['SOLR_CONFIGSET_NAME'] %>
  collection_name_prefix: 'catalog-prod-'
  shards: <%= ENV['SOLR_COLLECTION_SHARDS'] %>
  replicas: <%= ENV['SOLR_COLLECTION_REPLICAS'] %>
  webhook_action_commit_within_time_ms: 600000 # 10 min

redis:
  url: <%= ENV['REDIS_URL'] %>
  username: <%= ENV['REDIS_SIDEKIQ_USER'] %>
  password: <%= DockerSecrets.lookup(:redis_sidekiq_password) %>

# External Services
alma:
  api_key: <%= DockerSecrets.lookup(:alma_api_key) %>
  webhook_secret: <%= DockerSecrets.lookup(:alma_webhook_secret) %>
  publishing_job:
    name: 'Publishing Platform Job All Titles - Find Catalog - FTP'

sftp:
  host: <%= ENV.fetch('SFTP_HOST', 'move.library.upenn.edu') %>
  root: <%= ENV.fetch('SFTP_ROOT', '/almareload') %>
  username: <%= DockerSecrets.lookup(:sftp_username) %>
  password: <%= DockerSecrets.lookup(:sftp_password) %>
  parallel_downloads: 20

slack:
  api_key: '12345'

honeybadger:
  api_key: '12345'
