#
# Settings/Configuration shared among all environments.
#
# This configuration can be overridden in environment specific files.
#

# App Version
app_version: <%= ENV.fetch('APP_IMAGE_TAG', nil) %>

# External Services
honeybadger:
  api_key: '12345'
