---
# see https://github.com/sidekiq/sidekiq/wiki/Advanced-Options#the-sidekiq-configuration-file for config options

#:concurrency: 5
#staging:
#  :concurrency: 10
#production:
#  :concurrency: 10
#:queues:
#  - critical
#  - default
#  - low