version: '3.4'

services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  solr:
    image: solr:9
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
      - ./solr:/solr/config
    command:
      - bash
      - "-c"
      - "precreate-core catalog_dev /catalog_config; precreate-core catalog_test /catalog_config; solr-foreground;"
volumes:
  db_data:
  solr_data:
