---
solr_configsets:
  - name: "catalog-indexing"
    path: "roles/catalog-indexing/files/src/solr/conf/"

solr_docker_image_tag: 9.3.0

solr_proxy_host: "catalog-manager-stg01.library.upenn.int"

solr_limits_cpu: "4"
solr_limits_mem: "12G"

solr_custom_env_variables:
  SOLR_ADMIN_USERNAME: "{{ catalog_solr_vault_values.secret.username }}"
  SOLR_ADMIN_PASSWORD: "{{ catalog_solr_vault_values.secret.password }}"
  SOLR_ENABLE_AUTHENTICATION: "yes"
  SOLR_HEAP: "8G"
  SOLR_JAVA_MEM: "-Xms10G -Xmx10G"

solr_docker_volume_settings:
  solr-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/solr_03/solr-1-staging"
  solr-2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/solr_03/solr-2-staging"
  solr-3:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/solr_03/solr-3-staging"