---
roles:
  # the original repo can't handle python3 so we will use a fork until it can
  - name: atosatto.docker-swarm
    src: https://gitlab.library.upenn.edu/devops/ansible/ansible-dockerswarm.git
    scm: git
    version: master

  - name: postgres
    src: https://gitlab.library.upenn.edu/devops/ansible/roles/postgres.git
    scm: git
    version: main

  - name: solr
    src: https://gitlab.library.upenn.edu/devops/ansible/roles/solr.git
    scm: git
    version: 1.3.0

  - name: zoonavigator
    src: https://gitlab.library.upenn.edu/devops/ansible/roles/zoonavigator.git
    scm: git
    version: main
