version: '3.4'

services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  solrcloud:
    image: solr:9
    ports:
      - "8983:8983"
    volumes:
      - solrcloud_data:/var/solr
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -c
      - -f
  redis:
    image: redis:7
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'

volumes:
  db_data:
  solrcloud_data:
  redis_data:
