# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.4.4'

gem 'bcrypt_pbkdf'
gem 'bootsnap', require: false
gem 'bootstrap_form', '~> 5.0'
gem 'config'
gem 'cssbundling-rails'
gem 'devise'
gem 'dry-transaction'
gem 'ed25519'
gem 'faraday'
gem 'honeybadger'
gem 'importmap-rails'
gem 'kaminari'
gem 'net-sftp'
gem 'omniauth'
gem 'omniauth-rails_csrf_protection'
gem 'omniauth-saml'
gem 'pennmarc', '~> 1'
gem 'pg', '~> 1.1'
gem 'propshaft'
gem 'puma', '~> 6.0'
gem 'rails', '~> 8'
gem 'rsolr'
gem 'rubyzip'
gem 'sidekiq-pro', '~> 7', source: 'https://gems.contribsys.com'
gem 'traject'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'upennlib-rubocop', require: false

group :development, :test do
  gem 'byebug'
  gem 'capybara'
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '~> 6.0'
  gem 'rspec-rails', '~> 6.0.0'
  gem 'rubocop-factory_bot'
  gem 'selenium-webdriver'
  gem 'webmock'
end

group :test do
  gem 'rspec-sidekiq'
end

group :development do
  gem 'web-console'
end
