---
# @tag debug:description: Output the interpolated docker-compose.yml template as an object
- name: "Debug - Output docker-compose.yml object"
  ansible.builtin.debug:
    msg: "{{ lookup('template', 'docker-compose.yml.j2') }}"
  when: postgres_debug | default (false, true)
  tags:
    - debug

# @tag docker_secrets:description: Create versioned docker secrets
- name: Create versioned docker secrets
  community.docker.docker_secret:
    name: "{{ 'postgres_' ~ item.key ~ '_v' ~ item.value.version }}"
    data: "{{ item.value.value }}"
    state: present
  with_dict:
    - "{{ postgres_database_versioned_secrets }}"
  tags: versioned_secrets
  no_log: true

# @tag deploy:description: Deploy postgres
- name: Deploy postgres
  community.docker.docker_stack:
    name: "{{ postgres_docker_stack_name }}"
    compose:
      - "{{ lookup('template', postgres_templates_docker_compose_path) | from_yaml }}"
    state: present
  changed_when: false
