---
# @meta description: >
# Role to run a Postgres in Docker Swarm Mode
# @end
# @meta title: postgres
# @meta author: [Andrew Kimball]
galaxy_info:
  author: Andrew Kimball
  role_name: postgres
  description: Run a Postgres in Docker Swarm Mode
  min_ansible_version: "2.9"
  license: MIT

  platforms:
    - name: Alpine
      versions:
        - all
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
        - jammy

  galaxy_tags:
    - postgres

dependencies: []
