---
catalog_indexing_build_docker_image: false
catalog_indexing_image_name: "catalog-indexing"
catalog_indexing_image_registry: "gitlab.library.upenn.edu/dld/catalog/catalog-indexing"
catalog_indexing_image_tag: "development"
catalog_indexing_port: 3000
catalog_indexing_rails_env: "development"
catalog_indexing_replicas: 1
catalog_indexing_solr_url: "http://solr-1:8983"
catalog_indexing_solr_admin_url: "http://catalog-indexing-dev.library.upenn.int/solr1/#/"
catalog_indexing_url: "catalog-indexing-dev.library.upenn.edu"
catalog_indexing_versioned_secrets:
  rails_master_key:
    value: "d387ab7464fc5b8bb2e5c0dcd4105355"
    version: "1"
  solr_username:
    value: "{{ solr_custom_env_variables.SOLR_ADMIN_USERNAME }}"
    version: "1"
  solr_password:
    value: "{{ solr_custom_env_variables.SOLR_ADMIN_PASSWORD }}"
    version: "1"
  sftp_username:
    value: "{{ catalog_indexing_vault_values.secret.sftp_username }}"
    version: "{{ catalog_indexing_vault_values.metadata.version }}"
  sftp_password:
    value: "{{ catalog_indexing_vault_values.secret.sftp_password }}"
    version: "{{ catalog_indexing_vault_values.metadata.version }}"
  sidekiq_pro_credentials:
    value: "{{ dld_sidekiq_pro_vault_values.secret.credentials }}"
    version: "{{ dld_sidekiq_pro_vault_values.metadata.version }}"
  slack_webhook_url:
    value: "{{ catalog_indexing_vault_values.secret.slack_webhook_url }}"
    version: "{{ catalog_indexing_vault_values.metadata.version }}"
  alma_api_key:
    value: "{{ catalog_indexing_vault_values.secret.alma_api_key }}"
    version: "{{ catalog_indexing_vault_values.metadata.version }}"
