---
solr_collections:
  - name: catalog-indexing-development
    configset: catalog-indexing
    replicas: 1
    shards: 1
  - name: catalog-indexing-test
    configset: catalog-indexing
    replicas: 1
    shards: 1

solr_configsets:
  - name: "catalog-indexing"
    path: "roles/catalog-indexing/files/src/solr/conf/"

solr_docker_image_tag: 9.3.0

solr_proxy_host: "catalog-indexing-dev.library.upenn.int"

solr_instances: 1

solr_collection_replicas: 1

solr_custom_env_variables:
  SOLR_ENABLE_AUTHENTICATION: "yes"
  SOLR_ADMIN_USERNAME: "admin"
  SOLR_ADMIN_PASSWORD: "password"
  SOLR_OPTS: "-Dsolr.max.booleanClauses=2048"
