# Internal Services
solr:
  collection_name_prefix: 'catalog-prod-'
  shards: 6
  replicas: 2

# External Services
honeybadger:
  api_key: <%= DockerSecrets.lookup(:honeybadger_api_key) %>

slack:
  webhook_url: <%= DockerSecrets.lookup(:slack_webhook_url) %>

# Settings
indexing:
  max_skipped_per_file: 1000
  max_errors_per_file: 10
