# Internal Services
solr:
  collection_name_prefix: 'catalog-test-'
  url: <%= ENV.fetch('SOLR_URL', 'http://solr:8983') %>
  user: <%= DockerSecrets.lookup(:solr_username, 'admin') %>
  password: <%= DockerSecrets.lookup(:solr_password, 'Bitnami') %>

# Settings
indexing:
  max_skipped_per_file: 0
  max_errors_per_file: 0