# Internal Services
solr:
  collection_name_prefix: 'catalog-test-'
  replicas: <%= ENV.fetch('SOLR_COLLECTION_REPLICAS', 1) %>
  shards: <%= ENV.fetch('SOLR_COLLECTION_SHARDS', 1) %>
  configset: <%= ENV['SOLR_TEST_CONFIGNAME'] %>

# Settings
indexing:
  max_skipped_per_file: 0
  max_errors_per_file: 0