---
sidekiq:
  instances:
    - name: default
      queues:
        - high
        - medium
        - low
      concurrency: 4
      replicas: 5
    - name: priority
      queues:
        - high
      concurrency: 5
      replicas: 1
