---
- name: Create custom docker image
  community.docker.docker_image:
    build:
      args:
        RAILS_ENV: "{{ catalog_indexing_rails_env }}"
        BUNDLE_GEMS__CONTRIBSYS__COM: "{{ 'catalog_indexing_sidekiq_pro_credentials_v' ~ catalog_indexing_versioned_secrets.sidekiq_pro_credentials.version }}"
      dockerfile: "Dockerfile"
      path: "/catalog-indexing/ansible/roles/catalog-indexing/files/src/"
      target: "development"
      pull: true
    force_tag: true
    force_source: true
    name: "{{ catalog_indexing_image_name ~ ':' ~ catalog_indexing_image_tag }}"
    source: build
    state: present
