---
- name: "Create custom docker image"
  community.docker.docker_image_build:
    name: "{{ catalog_indexing_image_name ~ ':' ~ catalog_indexing_image_tag }}"
    path: "/catalog-indexing/ansible/roles/catalog-indexing/files/src/"
    dockerfile: "Dockerfile"
    target: "development"
    secrets:
      - id: sidekiq_pro_credentials
        type: value
        value: "{{ dld_sidekiq_pro_vault_values.secret.credentials }}"
    args:
        RAILS_ENV: "{{ catalog_indexing_rails_env }}"
