---
- name: "Provision Docker Swarm Cluster"
  hosts: all
  become: true
  collections:
    - ansible.utils
    - ansible.netcommon
  tasks:
    - ansible.builtin.import_tasks: "provision_docker.yml"

- name: "Bootstrap Solr server/s"
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Set up folders for Solr docker volumes
      when: (inventory_hostname in solr_nodes) and swarm_manager_solr_docker_volume_settings
      block:
        - name: Create a directory if it does not exist
          ansible.builtin.file:
            path: "{{ swarm_manager_solr_docker_volume_settings[item].driver_opts.device }}"
            state: directory
            mode: 0775
          loop: "{{ swarm_labels }}"
  vars:
    solr_nodes: "{{ dict(groups.all | zip(groups.all | map('extract', hostvars, 'swarm_labels'))) | dict2items | selectattr('value', 'search', 'solr-') | map(attribute='key') }}"
    swarm_manager_host: "{{ groups | dict2items | selectattr('key', 'search', 'docker_swarm_manager') | map(attribute='value') | flatten | first }}"
    swarm_manager_solr_docker_volume_settings: "{{ hostvars[swarm_manager_host].solr_docker_volume_settings }}"
    swarm_labels: "{{ hostvars[inventory_hostname].swarm_labels | select('match', 'solr-') }}"

- name: "Deploy application"
  hosts: docker_swarm_manager
  become: true
  gather_facts: true
  tasks:
    - ansible.builtin.import_role:
        name: catalog-indexing
        tasks_from: symlink_project
      tags: catalog-indexing
    - ansible.builtin.import_role:
        name: traefik
      tags: traefik
    - ansible.builtin.import_role:
        name: zookeeper
      tags: zookeeper
    - ansible.builtin.import_role:
        name: zoonavigator
      tags: zoonavigator
      when: not is_development | default (false, true)
    - ansible.builtin.import_role:
        name: solr
      tags: solr
    - ansible.builtin.import_role:
        name: redis
      tags: redis
    - ansible.builtin.import_role:
        name: postgres
      tags: postgres
    - ansible.builtin.import_role:
        name: catalog-indexing
      tags: catalog-indexing
    - ansible.builtin.import_role:
        name: sidekiq
      tags: sidekiq
  post_tasks:
    - name: Recursively remove project directory
      ansible.builtin.file:
        path: "{{ project_root }}"
        state: absent
    - name: Prune images that are older than 2+ hours
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: false
          until: 2h
      when: not is_development | default (false, true)
